#!/bin/bash

set +e

while IFS= read -r line
do
rm -rf $line
done < /var/.libboost_mingw/files.list

rm -r /usr/i686-w64-mingw32/include/boost/ /usr/x86_64-w64-mingw32/include/boost/
rm -rf /var/.libboost_mingw
