#!/bin/bash

set -e
wget https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.2-linux-x86_64.tar.gz -O /tmp/julia.tar.gz
tar -xzf /tmp/julia.tar.gz -C /opt
ln -s /opt/julia-1.9.2/bin/julia /usr/bin/julia
rm -f /tmp/julia.tar.gz
